/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCashRouteImport } from './routes/_authenticated/cash'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as GuestTokenRouteImport } from './routes/guest.$token'
import { Route as AuthenticatedStaysIdRouteImport } from './routes/_authenticated/stays.$id'
import { Route as AuthenticatedStaysNewRouteImport } from './routes/_authenticated/stays.new'
import { Route as AuthenticatedStaysIdEditRouteImport } from './routes/_authenticated/stays.$id_.edit'
import { Route as ApiPublicPaypalCreateOrderRouteImport } from './routes/api/public/paypal.create-order'
import { Route as ApiPublicPaypalReturnRouteImport } from './routes/api/public/paypal.return'
import { Route as ApiPublicPaypalStatusRouteImport } from './routes/api/public/paypal.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashRoute = AuthenticatedCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuestTokenRoute = GuestTokenRouteImport.update({
  id: '/guest/$token',
  path: '/guest/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaysIdRoute = AuthenticatedStaysIdRouteImport.update({
  id: '/stays/$id',
  path: '/stays/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaysNewRoute = AuthenticatedStaysNewRouteImport.update({
  id: '/stays/new',
  path: '/stays/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaysIdEditRoute =
  AuthenticatedStaysIdEditRouteImport.update({
    id: '/stays/$id_/edit',
    path: '/stays/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaypalCreateOrderRoute =
  ApiPublicPaypalCreateOrderRouteImport.update({
    id: '/api/public/paypal/create-order',
    path: '/api/public/paypal/create-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalReturnRoute = ApiPublicPaypalReturnRouteImport.update({
  id: '/api/public/paypal/return',
  path: '/api/public/paypal/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalStatusRoute = ApiPublicPaypalStatusRouteImport.update({
  id: '/api/public/paypal/status',
  path: '/api/public/paypal/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cash': typeof AuthenticatedCashRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/guest/$token': typeof GuestTokenRoute
  '/stays/$id': typeof AuthenticatedStaysIdRoute
  '/stays/new': typeof AuthenticatedStaysNewRoute
  '/stays/$id/edit': typeof AuthenticatedStaysIdEditRoute
  '/api/public/paypal/create-order': typeof ApiPublicPaypalCreateOrderRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/status': typeof ApiPublicPaypalStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cash': typeof AuthenticatedCashRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/guest/$token': typeof GuestTokenRoute
  '/stays/$id': typeof AuthenticatedStaysIdRoute
  '/stays/new': typeof AuthenticatedStaysNewRoute
  '/stays/$id/edit': typeof AuthenticatedStaysIdEditRoute
  '/api/public/paypal/create-order': typeof ApiPublicPaypalCreateOrderRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/status': typeof ApiPublicPaypalStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/cash': typeof AuthenticatedCashRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/guest/$token': typeof GuestTokenRoute
  '/_authenticated/stays/$id': typeof AuthenticatedStaysIdRoute
  '/_authenticated/stays/new': typeof AuthenticatedStaysNewRoute
  '/_authenticated/stays/$id_/edit': typeof AuthenticatedStaysIdEditRoute
  '/api/public/paypal/create-order': typeof ApiPublicPaypalCreateOrderRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/status': typeof ApiPublicPaypalStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/calendar'
    | '/cash'
    | '/dashboard'
    | '/home'
    | '/requests'
    | '/services'
    | '/guest/$token'
    | '/stays/$id'
    | '/stays/new'
    | '/stays/$id/edit'
    | '/api/public/paypal/create-order'
    | '/api/public/paypal/return'
    | '/api/public/paypal/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/calendar'
    | '/cash'
    | '/dashboard'
    | '/home'
    | '/requests'
    | '/services'
    | '/guest/$token'
    | '/stays/$id'
    | '/stays/new'
    | '/stays/$id/edit'
    | '/api/public/paypal/create-order'
    | '/api/public/paypal/return'
    | '/api/public/paypal/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/activity'
    | '/_authenticated/calendar'
    | '/_authenticated/cash'
    | '/_authenticated/dashboard'
    | '/_authenticated/home'
    | '/_authenticated/requests'
    | '/_authenticated/services'
    | '/guest/$token'
    | '/_authenticated/stays/$id'
    | '/_authenticated/stays/new'
    | '/_authenticated/stays/$id_/edit'
    | '/api/public/paypal/create-order'
    | '/api/public/paypal/return'
    | '/api/public/paypal/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestTokenRoute: typeof GuestTokenRoute
  ApiPublicPaypalCreateOrderRoute: typeof ApiPublicPaypalCreateOrderRoute
  ApiPublicPaypalReturnRoute: typeof ApiPublicPaypalReturnRoute
  ApiPublicPaypalStatusRoute: typeof ApiPublicPaypalStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash': {
      id: '/_authenticated/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AuthenticatedCashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/guest/$token': {
      id: '/guest/$token'
      path: '/guest/$token'
      fullPath: '/guest/$token'
      preLoaderRoute: typeof GuestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stays/$id': {
      id: '/_authenticated/stays/$id'
      path: '/stays/$id'
      fullPath: '/stays/$id'
      preLoaderRoute: typeof AuthenticatedStaysIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stays/new': {
      id: '/_authenticated/stays/new'
      path: '/stays/new'
      fullPath: '/stays/new'
      preLoaderRoute: typeof AuthenticatedStaysNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stays/$id_/edit': {
      id: '/_authenticated/stays/$id_/edit'
      path: '/stays/$id/edit'
      fullPath: '/stays/$id/edit'
      preLoaderRoute: typeof AuthenticatedStaysIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paypal/create-order': {
      id: '/api/public/paypal/create-order'
      path: '/api/public/paypal/create-order'
      fullPath: '/api/public/paypal/create-order'
      preLoaderRoute: typeof ApiPublicPaypalCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/return': {
      id: '/api/public/paypal/return'
      path: '/api/public/paypal/return'
      fullPath: '/api/public/paypal/return'
      preLoaderRoute: typeof ApiPublicPaypalReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/status': {
      id: '/api/public/paypal/status'
      path: '/api/public/paypal/status'
      fullPath: '/api/public/paypal/status'
      preLoaderRoute: typeof ApiPublicPaypalStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCashRoute: typeof AuthenticatedCashRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedStaysIdRoute: typeof AuthenticatedStaysIdRoute
  AuthenticatedStaysNewRoute: typeof AuthenticatedStaysNewRoute
  AuthenticatedStaysIdEditRoute: typeof AuthenticatedStaysIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCashRoute: AuthenticatedCashRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedStaysIdRoute: AuthenticatedStaysIdRoute,
  AuthenticatedStaysNewRoute: AuthenticatedStaysNewRoute,
  AuthenticatedStaysIdEditRoute: AuthenticatedStaysIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestTokenRoute: GuestTokenRoute,
  ApiPublicPaypalCreateOrderRoute: ApiPublicPaypalCreateOrderRoute,
  ApiPublicPaypalReturnRoute: ApiPublicPaypalReturnRoute,
  ApiPublicPaypalStatusRoute: ApiPublicPaypalStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
